### ISSUE TITLE
[챕터 2] LogSoftMax의 derivative

### ISSUE THREAD

**Issue by yskim0** [yskim0/NYU-DEEP-LEARNING#4]
2주차 강의 16슬라이드에서 LogSoftMax의 derivative를 직접 구하라 하고 넘어가셨는데,
제 풀이가 맞는지 모르겠어서 이슈로 올립니다.
틀린 점이나 질문이 있다면 코멘트 달아주세요

![image](https://user-images.githubusercontent.com/48315997/90759161-05d9bf80-e31b-11ea-8632-5533aad6b0f7.png)

![image](https://user-images.githubusercontent.com/48315997/90759250-2570e800-e31b-11ea-9115-cf1706a2dcb5.png)

**Comment by leahincom** [comment]
맞는 것 같습니다.
